# Spring properties
spring:
  application:
    name: msg-comsumer  # Identify this application
  freemarker:
    enabled: false     # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false       # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/templates/    # Trailing / mandatory
                       # Template location for this application only
#  dubbo:
#    scan: com
#    application:
#      name: comment-comsuner
#    registry:
#      protocol: zookeeper
#      address: 127.0.0.1:2181
#    protocol:
#      name: duubo
#      port: 20880
#      serialization: kryo

# Map the error path to error template (for Thymeleaf)
error:
  path=/error

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#eureka:
#  instance:
#    statusPageUrl: https://${eureka.hostname}/info
#    healthCheckUrl: https://${eureka.hostname}/health
#    homePageUrl: https://${eureka.hostname}/

# HTTP Server
server:
  port: 18088   # HTTP (Tomcat) port
#  context-path: /msg-comsumer


## acutor 设置
management:
  port: 18081
  address: 127.0.0.1
  security:
    enabled: false
    role: SUPERUSER

security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin




